/**
 * Pull the tournament season leading into a given International, from
 * Liquipedia's own tier listing pages:
 *   https://liquipedia.net/dota2/Tier_1_Tournaments   (Majors, The International)
 *   https://liquipedia.net/dota2/Tier_2_Tournaments   (where DPC Minors sit)
 *
 *   npm run research:liquipedia -- ti08 2017,2018
 *
 * Those pages already carry exactly what a season-overview chart needs, per
 * year: tournament, date, prize pool, location, winner and runner-up (each
 * with a team logo). Crucially the TIER is Liquipedia's own classification,
 * not our judgment call — which is the whole point. The owner wants the
 * archive to "reflect the history of each year with the years where the
 * Major + Minors existed and the years where they went away from that
 * system", and that comparison is only honest if the tiering comes from a
 * consistent external source rather than from us deciding per year what
 * counted as big. Pulling both tiers is what makes the Minor layer visible:
 * a season with a Major/Minor structure and one without look nothing alike,
 * and tier 1 alone cannot show the difference.
 *
 * WHY MULTIPLE YEARS, AND WHY A CUTOFF: a DPC season does not line up with a
 * calendar year. The 2017-18 season opened in late 2017 and ended at TI8 in
 * August 2018, while the calendar year 2018 also contains the Kuala Lumpur
 * Major — which belongs to the NEXT season entirely. So the years given are
 * merged, then everything starting after the event's final day is dropped.
 * The International itself is kept: it is the end of the story, not outside it.
 *
 * TERMS OF USE (https://liquipedia.net/api-terms-of-use), as recorded in
 * scripts/ingest-liquipedia.ts and observed here:
 *
 *   - MediaWiki API only; scraping rendered liquipedia.net pages is forbidden.
 *     This uses the API. It does use `action=parse`, which the sibling ingest
 *     script deliberately avoids — unavoidable here, because this table is
 *     generated by a Lua/LPDB widget and simply is not present in the page's
 *     wikitext. There is nothing to parse client-side without it.
 *   - `action=parse` is capped at 1 request per 30 SECONDS, far stricter than
 *     the usual 1-per-2s. This script makes one parse request per tier page
 *     and caches each, so a re-run costs zero requests. Adding a tier costs
 *     one more request and 30 more seconds on the first run only.
 *   - Custom User-Agent identifying the project. From lib/http.ts.
 *   - Cache results, do not re-request. fetchJsonCached writes to data/raw/.
 *   - Content is CC-BY-SA 3.0 and MUST be attributed wherever displayed.
 *     The attribution string travels in the output JSON so it reaches the UI.
 *
 * Liquipedia is blocked from this project's cloud dev sandbox, so — like
 * research-wayback.ts and research-gosugamers.ts — this has to run on a real
 * machine. The row parsing below is a first pass written without ever having
 * seen this page's rendered markup; if it returns 0 rows, the cached HTML it
 * names has the real structure to correct it against.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { fetchJsonCached } from './lib/http.ts';
import { loadEvent } from './lib/events.ts';

const API = 'https://liquipedia.net/dota2/api.php';
/**
 * Tier 1 is the Majors and The International; tier 2 is where the DPC Minors
 * live. Both are needed to show a season's actual shape — a Major-and-Minor
 * year looks completely different from one without that structure, and that
 * contrast is invisible if only tier 1 is pulled.
 */
const TIER_PAGES: { tier: number; page: string }[] = [
  { tier: 1, page: 'Tier_1_Tournaments' },
  { tier: 2, page: 'Tier_2_Tournaments' },
];
/** Their documented cap for action=parse specifically. Not the 2s general limit. */
const PARSE_INTERVAL_MS = 30_000;

export const ATTRIBUTION =
  'Tournament, prize pool and tier data from Liquipedia, licensed CC-BY-SA 3.0.';

interface ParseResponse {
  parse?: { text?: { '*': string } };
  error?: { info: string };
}

async function fetchRenderedHtml(page: string, cacheDir: string): Promise<string> {
  const url = `${API}?action=parse&page=${encodeURIComponent(page)}&prop=text&format=json`;
  const { data, cached } = await fetchJsonCached<ParseResponse>(url, {
    cachePath: `${cacheDir}/liquipedia/${page.replace(/[^A-Za-z0-9]/g, '_')}.parse.json`,
    minIntervalMs: PARSE_INTERVAL_MS,
  });
  if (data.error) throw new Error(`${page} -> API error: ${data.error.info}`);
  const html = data.parse?.text?.['*'];
  if (!html) throw new Error(`${page} -> no HTML in API response`);
  console.log(cached ? '  (served from local cache — no request made)' : '  (fetched from Liquipedia)');
  return html;
}

/**
 * Every heading id on a page, in document order.
 *
 * Printed when a year's section can't be found. A page that organises its
 * content differently is the likeliest cause, and guessing at the structure
 * from the outside wastes a 30-second rate-limited request per attempt —
 * far better to have the script say what is actually there.
 */
function headingIds(html: string): string[] {
  const ids: string[] = [];
  for (const match of html.matchAll(/<h[1-6][^>]*>[\s\S]*?<\/h[1-6]>/gi)) {
    const id = /id="([^"]+)"/i.exec(match[0])?.[1];
    if (id) ids.push(id);
  }
  return ids;
}

/** Isolates one year's section: from its heading to the next heading of any level. */
function extractYearSection(html: string, year: string): string | null {
  const headingRe = new RegExp(`<h[1-6][^>]*id="${year}"[^>]*>[\\s\\S]*?</h[1-6]>`, 'i');
  const spanRe = new RegExp(
    `<h[1-6][^>]*>[\\s\\S]{0,200}?id="${year}"[\\s\\S]*?</h[1-6]>`,
    'i',
  );
  const start = headingRe.exec(html) ?? spanRe.exec(html);
  if (!start) return null;
  const from = start.index + start[0].length;
  const next = /<h[1-6][^>]*>/i.exec(html.slice(from));
  return html.slice(from, next ? from + next.index : html.length);
}

const decodeEntities = (text: string): string =>
  text
    .replace(/&nbsp;/g, ' ')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&ndash;/g, '–')
    .replace(/&mdash;/g, '—')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    // Liquipedia escapes underscores in class names as &#95;, which otherwise
    // survives into the output as literal "&#95;" instead of "_".
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)))
    // Ampersand last, so a literal "&amp;#95;" isn't double-decoded.
    .replace(/&amp;/g, '&');

const stripTags = (html: string): string =>
  decodeEntities(html.replace(/<[^>]+>/g, ' '))
    .replace(/\s+/g, ' ')
    .trim();

const absoluteUrl = (src: string): string =>
  src.startsWith('//') ? `https:${src}` : src.startsWith('/') ? `https://liquipedia.net${src}` : src;

interface TeamRef {
  name: string | null;
  logo_url: string | null;
  /**
   * Liquipedia files carry a theme suffix: "allmode" works on any background,
   * while "lightmode" is drawn for light backgrounds and can be near-invisible
   * on a dark one (there is usually a "darkmode" counterpart). The archive
   * renders in both themes, so this has to be recorded, not discovered later
   * as a black-on-black logo.
   */
  logo_variant: 'allmode' | 'lightmode' | 'darkmode' | 'unknown' | null;
}

function logoVariant(url: string | null): TeamRef['logo_variant'] {
  if (!url) return null;
  if (/allmode/i.test(url)) return 'allmode';
  if (/lightmode/i.test(url)) return 'lightmode';
  if (/darkmode/i.test(url)) return 'darkmode';
  return 'unknown';
}

/** A winner/runner-up cell: a team-icon image plus a linked team name. */
function extractTeamCell(cellHtml: string): TeamRef {
  const img = /<img[^>]+src="([^"]+)"/i.exec(cellHtml);
  const links = [...cellHtml.matchAll(/<a[^>]*title="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)];
  // Skip the image's own File: link; the team name is the one with real text.
  const nameLink = links.find((m) => !/^File:/i.test(m[1] ?? '') && stripTags(m[2] ?? ''));
  const name = nameLink ? stripTags(nameLink[2] ?? '') : stripTags(cellHtml);
  // "TBD" is Liquipedia's placeholder for an unfinished event, not a team.
  const real = name && name.toUpperCase() !== 'TBD' ? name : null;
  const logoUrl = img ? absoluteUrl(img[1]!) : null;
  return { name: real, logo_url: logoUrl, logo_variant: logoVariant(logoUrl) };
}

const MONTHS: Record<string, number> = {
  jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
  jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
};

/**
 * Turns Liquipedia's displayed date range into the event's START date, as
 * YYYY-MM-DD, for sorting and for the cutoff.
 *
 * Observed shapes, all from real output:
 *   "Aug 15–25, 2018"            single month
 *   "Apr 27 – May 06, 2018"      spans two months
 *   "Nov 09–18, 2018"
 *
 * A season-opening event can also span New Year, which Liquipedia writes with
 * the year attached to the start ("Dec 28, 2017 – Jan 05, 2018"). That inline
 * year must win over the trailing one, or a December event lands twelve months
 * late. Returns null rather than guessing when nothing matches — an unparsed
 * date is reported, never silently dropped or defaulted.
 */
function parseStartDate(display: string | null): string | null {
  if (!display) return null;
  const text = display.replace(/–|—/g, '-').trim();

  const head = /^([A-Za-z]{3})[a-z]*\s+(\d{1,2})(?:\s*,\s*(\d{4}))?/.exec(text);
  if (!head) return null;

  const month = MONTHS[head[1]!.toLowerCase()];
  if (!month) return null;
  const day = Number(head[2]);

  // Prefer a year stated right after the start day; fall back to the trailing one.
  const year = Number(head[3] ?? /(\d{4})\s*$/.exec(text)?.[1]);
  if (!Number.isFinite(year) || !Number.isFinite(day)) return null;

  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

/**
 * The END date of a displayed range, as YYYY-MM-DD.
 *
 * Needed to place the season's front boundary at the previous International's
 * final day rather than at a calendar-year edge. Shapes, from real output:
 *   "Aug 02–12, 2017"        -> 2017-08-12   (end month implied by the start)
 *   "Apr 27 – May 06, 2018"  -> 2018-05-06   (end month stated)
 *   "Jan 19–21, 2018"        -> 2018-01-21
 */
function parseEndDate(display: string | null): string | null {
  if (!display) return null;
  const text = display.replace(/–|—/g, '-').trim();
  const year = Number(/(\d{4})\s*$/.exec(text)?.[1]);
  if (!Number.isFinite(year)) return null;

  // "- May 06" — the tail names its own month.
  const withMonth = /-\s*([A-Za-z]{3})[a-z]*\s+(\d{1,2})/.exec(text);
  if (withMonth) {
    const month = MONTHS[withMonth[1]!.toLowerCase()];
    if (!month) return null;
    return `${year}-${String(month).padStart(2, '0')}-${String(Number(withMonth[2])).padStart(2, '0')}`;
  }

  // "Aug 02-12" — the tail is a bare day in the start's month.
  const bareDay = /^([A-Za-z]{3})[a-z]*\s+\d{1,2}\s*-\s*(\d{1,2})/.exec(text);
  if (bareDay) {
    const month = MONTHS[bareDay[1]!.toLowerCase()];
    if (!month) return null;
    return `${year}-${String(month).padStart(2, '0')}-${String(Number(bareDay[2])).padStart(2, '0')}`;
  }

  // Single-day event: end is the start.
  return parseStartDate(display);
}

/**
 * "$25,532,177" -> 25532177. Null when the cell isn't a plain USD figure —
 * some events list a non-USD currency or a placeholder, and converting or
 * guessing at those would be inventing a number.
 */
function parsePrizeUsd(display: string | null): number | null {
  if (!display) return null;
  const match = /^\$\s*([\d,]+)/.exec(display.trim());
  if (!match) return null;
  const value = Number(match[1]!.replace(/,/g, ''));
  return Number.isFinite(value) && value > 0 ? value : null;
}

interface TierOneRow {
  /** Liquipedia's own tier, from which page the row came off. */
  tier: number;
  tournament: string | null;
  tournament_url: string | null;
  date: string | null;
  /** Derived from `date` for sorting and the season cutoff. Null if unparsed. */
  start_date: string | null;
  end_date: string | null;
  /** Derived from `prizepool`. Null when the cell isn't a plain USD amount. */
  prizepool_usd: number | null;
  prizepool: string | null;
  location: string | null;
  /** Team count, Liquipedia's "P#" column. */
  participants: string | null;
  /**
   * Liquipedia highlights Valve-sponsored events (Majors and The
   * International) with a row class. Kept raw rather than reduced to a
   * boolean: the exact marker is the evidence, and what counts as "special"
   * changed across eras — which is the thing the season chart is meant to show.
   */
  row_classes: string | null;
  winner: TeamRef;
  runner_up: TeamRef;
}

function parseRows(sectionHtml: string, tier: number): TierOneRow[] {
  const rows: TierOneRow[] = [];

  for (const rowMatch of sectionHtml.matchAll(/<tr([^>]*)>([\s\S]*?)<\/tr>/gi)) {
    const rowAttrs = rowMatch[1] ?? '';
    const rowHtml = rowMatch[2]!;
    const cells = [...rowHtml.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map((m) => m[1]!);
    // Header and spacer rows don't carry a full complement of columns.
    if (cells.length < 7) continue;
    if (/<th[^>]*>/i.test(rowHtml) && !/<td[^>]*>/i.test(rowHtml)) continue;

    // Column order, confirmed against real output:
    //   0 icon | 1 tournament | 2 date | 3 prize pool | 4 location | 5 P# |
    //   6 winner | 7 runner-up
    // The icon cell links to the tournament too, so fall back to it for the
    // name if the name cell somehow parses empty.
    const nameCell = cells[1] ?? '';
    const link =
      /<a[^>]+href="([^"]+)"[^>]*title="([^"]+)"/i.exec(nameCell) ??
      /<a[^>]+href="([^"]+)"[^>]*title="([^"]+)"/i.exec(cells[0] ?? '');
    const tournament = stripTags(nameCell) || (link ? link[2]! : null);
    if (!tournament) continue;

    const date = stripTags(cells[2] ?? '') || null;
    const prizepool = stripTags(cells[3] ?? '') || null;

    rows.push({
      tier,
      tournament,
      tournament_url: link ? absoluteUrl(link[1]!) : null,
      date,
      start_date: parseStartDate(date),
      end_date: parseEndDate(date),
      prizepool_usd: parsePrizeUsd(prizepool),
      prizepool,
      location: stripTags(cells[4] ?? '') || null,
      participants: stripTags(cells[5] ?? '') || null,
      row_classes: /class="([^"]*)"/i.exec(rowAttrs)?.[1] ?? null,
      winner: extractTeamCell(cells[6] ?? ''),
      runner_up: extractTeamCell(cells[7] ?? ''),
    });
  }
  return rows;
}

async function main(): Promise<void> {
  const key = process.argv[2];
  const yearsArg = process.argv[3];
  if (!key || !yearsArg) {
    console.error(
      'usage: npm run research:liquipedia -- <event-key> <years>   (e.g. ti08 2017,2018)',
    );
    process.exit(1);
  }
  const years = yearsArg.split(',').map((y) => y.trim()).filter(Boolean);

  const event = await loadEvent(key);
  // The season ends when the event does. Everything starting after the final
  // day belongs to the next season, not this story.
  const cutoff = event.phases.at(-1)?.to ?? `${event.year}-12-31`;

  const cacheDir = fileURLToPath(new URL(`../data/raw/${key}`, import.meta.url));
  const liquipediaDir = fileURLToPath(new URL(`../data/raw/${key}/liquipedia/`, import.meta.url));
  await mkdir(liquipediaDir, { recursive: true });

  console.log(`${event.name}`);
  console.log(`Liquipedia tiers: ${TIER_PAGES.map((t) => t.tier).join(', ')}`);
  console.log(`years: ${years.join(', ')}`);
  console.log(`season cutoff: events starting after ${cutoff} are dropped`);
  console.log(
    `note: action=parse is capped at 1 request / 30s, so an uncached run of ` +
      `${TIER_PAGES.length} pages takes about ${(TIER_PAGES.length - 1) * 30}s of waiting.\n`,
  );

  const all: TierOneRow[] = [];

  for (const { tier, page } of TIER_PAGES) {
    console.log(`tier ${tier} — ${page}`);
    const html = await fetchRenderedHtml(page, cacheDir);

    const debugPath = `${liquipediaDir}${page}.html`;
    await writeFile(debugPath, html, 'utf8');

    let anyFound = false;
    for (const year of years) {
      const section = extractYearSection(html, year);
      if (!section) {
        console.log(`  ${year}: no heading found`);
        continue;
      }
      anyFound = true;
      const parsed = parseRows(section, tier);
      console.log(`  ${year}: ${parsed.length} row(s)`);
      all.push(...parsed);
    }

    if (!anyFound) {
      const ids = headingIds(html);
      console.log(`\n  ${page} has no section for any requested year. Headings it does have (${ids.length}):`);
      console.log(`    ${ids.slice(0, 60).join(', ') || '(none at all — the page may not use headings)'}`);
      if (ids.length > 60) console.log(`    ...and ${ids.length - 60} more`);
      const rowCount = [...html.matchAll(/<tr[^>]*>/gi)].length;
      console.log(`  the page does contain ${rowCount} table row(s), so the data may be laid out another way.`);
      console.log(`  full HTML: ${debugPath}\n`);
    }
  }

  // An event listed on both tier pages would otherwise be charted twice.
  // Liquipedia's stricter classification wins, so tier 1 beats tier 2.
  const byIdentity = new Map<string, TierOneRow>();
  const duplicates: TierOneRow[] = [];
  for (const row of all.sort((a, b) => a.tier - b.tier)) {
    const identity = `${row.tournament}|${row.start_date}`;
    const existing = byIdentity.get(identity);
    if (existing) {
      duplicates.push(row);
      continue;
    }
    byIdentity.set(identity, row);
  }
  if (duplicates.length) {
    console.log(`\n${duplicates.length} row(s) appeared on more than one tier page; kept the lower tier:`);
    for (const row of duplicates) console.log(`  tier ${row.tier}  ${row.tournament}`);
  }
  const deduped = [...byIdentity.values()];

  // Report anything undated before filtering — a row dropped for an unparsed
  // date would otherwise vanish without explanation.
  const undated = deduped.filter((r) => !r.start_date);

  /**
   * The season's front boundary is the PREVIOUS International's last day, not
   * a calendar-year edge — a competitive season runs TI to TI. Derived from
   * the table's own rows rather than hardcoded, so it stays correct for every
   * year this is pointed at. Absent (TI1), the window simply opens earlier.
   */
  const previousTi = deduped
    .filter(
      (r) =>
        /^The International/i.test(r.tournament ?? '') &&
        r.start_date &&
        r.start_date < (event.phases[0]?.from ?? cutoff),
    )
    .sort((a, b) => a.start_date!.localeCompare(b.start_date!))
    .at(-1);
  const seasonStart = previousTi?.end_date ?? previousTi?.start_date ?? null;
  if (previousTi) {
    console.log(
      `\nseason start: the day after ${previousTi.tournament} ended (${seasonStart})`,
    );
  } else {
    console.log('\nseason start: no previous International found in these years — no front cutoff');
  }

  const inWindow = (r: TierOneRow): boolean =>
    !!r.start_date && r.start_date <= cutoff && (!seasonStart || r.start_date > seasonStart);

  const afterCutoff = deduped.filter((r) => r.start_date && r.start_date > cutoff);
  const beforeSeason = deduped.filter(
    (r) => r.start_date && seasonStart && r.start_date <= seasonStart,
  );
  const rows = deduped.filter(inWindow).sort((a, b) => a.start_date!.localeCompare(b.start_date!));

  const t1 = rows.filter((r) => r.tier === 1).length;
  const t2 = rows.filter((r) => r.tier === 2).length;
  console.log(
    `\n${rows.length} event(s) in the season leading into ${event.name} ` +
      `(${t1} tier-1, ${t2} tier-2):\n`,
  );
  for (const row of rows) {
    // Liquipedia's own legend: highlighted rows are Valve-sponsored events.
    const valve = /row--highlighted/.test(row.row_classes ?? '') ? ' ★valve' : '';
    console.log(
      `  ${row.start_date}  T${row.tier}  ${(row.tournament ?? '?').padEnd(38)} ` +
        `${(row.prizepool ?? '?').padStart(12)}  ${(row.participants ?? '?').padStart(2)}t${valve}`,
    );
    console.log(
      `        winner: ${(row.winner.name ?? '(not parsed)').padEnd(24)} ${row.winner.logo_url ?? '(no logo)'}`,
    );
  }

  if (afterCutoff.length) {
    console.log(`\ndropped ${afterCutoff.length} event(s) starting after ${cutoff} (next season):`);
    for (const row of afterCutoff) console.log(`  ${row.start_date}  ${row.tournament}`);
  }
  if (beforeSeason.length) {
    console.log(`\ndropped ${beforeSeason.length} event(s) at or before ${seasonStart} (previous season):`);
    for (const row of beforeSeason) console.log(`  ${row.start_date}  ${row.tournament}`);
  }
  if (undated.length) {
    console.log(`\n${undated.length} row(s) had a date this script could not parse — NOT included:`);
    for (const row of undated) console.log(`  "${row.date}"  ${row.tournament}`);
  }
  const missingLogo = rows.filter((r) => r.winner.name && !r.winner.logo_url);
  if (missingLogo.length) {
    console.log(`\n${missingLogo.length} included row(s) have a winner but no logo URL:`);
    for (const row of missingLogo) console.log(`  ${row.tournament} — ${row.winner.name}`);
  }
  const missingPrize = rows.filter((r) => r.prizepool_usd === null);
  if (missingPrize.length) {
    console.log(`\n${missingPrize.length} included row(s) have no parseable USD prize pool:`);
    for (const row of missingPrize) console.log(`  ${row.tournament} — "${row.prizepool}"`);
  }
  const lightOnly = rows.filter((r) => r.winner.logo_variant === 'lightmode');
  if (lightOnly.length) {
    console.log(
      `\n${lightOnly.length} winner logo(s) are "lightmode" files — these can disappear against the ` +
        `archive's dark theme and need their darkmode counterpart before use:`,
    );
    for (const row of lightOnly) console.log(`  ${row.winner.name}  (${row.tournament})`);
  }

  const outDir = fileURLToPath(new URL('../data/research/', import.meta.url));
  await mkdir(outDir, { recursive: true });
  const outPath = `${outDir}${key}.liquipedia-tournaments.json`;
  await writeFile(
    outPath,
    `${JSON.stringify(
      {
        _note:
          "Tier-1 and tier-2 tournaments in the season leading into this event, from Liquipedia's " +
          "own tier listing pages. Tier classification, prize pool and winner are Liquipedia's, " +
          'not inferred by this project. prizepool is the TOTAL pool as listed, NOT the ' +
          'first-place share. row_classes carries Liquipedia\'s own highlight marker, whose ' +
          'legend reads "special Dota Major Championships and The International events which are ' +
          'sponsored by Valve" — the evidence for whether an event was Valve-backed in that year. ' +
          'Rows outside the season window, or whose date could not be parsed, were dropped and are ' +
          'listed in _excluded so nothing disappears silently.',
        _generated_by: 'scripts/research-liquipedia-tier1.ts',
        _generated_at: new Date().toISOString(),
        _attribution: ATTRIBUTION,
        _sources: TIER_PAGES.map(({ tier, page }) => ({
          tier,
          type: 'url',
          url: `https://liquipedia.net/dota2/${page}`,
          retrieved_at: new Date().toISOString(),
        })),
        event: key,
        years,
        tiers: TIER_PAGES.map((t) => t.tier),
        season_window: {
          from_exclusive: seasonStart,
          from_basis: previousTi ? `end of ${previousTi.tournament}` : 'none found in these years',
          to_inclusive: cutoff,
          to_basis: `final day of ${event.name}, from data/sources/events.json`,
        },
        row_count: rows.length,
        tier_counts: { tier1: t1, tier2: t2 },
        _excluded: {
          after_cutoff: afterCutoff.map((r) => ({ tournament: r.tournament, start_date: r.start_date })),
          before_season: beforeSeason.map((r) => ({ tournament: r.tournament, start_date: r.start_date })),
          unparsed_date: undated.map((r) => ({ tournament: r.tournament, date: r.date })),
          duplicate_across_tiers: duplicates.map((r) => ({ tournament: r.tournament, tier: r.tier })),
        },
        rows,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
  console.log(`\nwrote ${rows.length} row(s) -> ${outPath}`);
  console.log(`\n${ATTRIBUTION}`);
}

main().catch((error: unknown) => {
  console.error(`\nFAILED: ${(error as Error).message}`);
  process.exit(1);
});
