/**
 * Pull one year's Tier 1 tournaments from Liquipedia's own
 * "Tier 1 Tournaments" page: https://liquipedia.net/dota2/Tier_1_Tournaments
 *
 *   npm run research:liquipedia -- ti08 2018
 *
 * That page already carries exactly what a season-overview chart needs, per
 * year: tournament, date, prize pool, location, winner and runner-up (each
 * with a team logo). Crucially the TIER is Liquipedia's own classification,
 * not our judgment call — which is the whole point. The owner wants the
 * archive to "reflect the history of each year with the years where the
 * Major + Minors existed and the years where they went away from that
 * system", and that comparison is only honest if the tiering comes from a
 * consistent external source rather than from us deciding per year what
 * counted as big.
 *
 * TERMS OF USE (https://liquipedia.net/api-terms-of-use), as recorded in
 * scripts/ingest-liquipedia.ts and observed here:
 *
 *   - MediaWiki API only; scraping rendered liquipedia.net pages is forbidden.
 *     This uses the API. It does use `action=parse`, which the sibling ingest
 *     script deliberately avoids — unavoidable here, because this table is
 *     generated by a Lua/LPDB widget and simply is not present in the page's
 *     wikitext. There is nothing to parse client-side without it.
 *   - `action=parse` is capped at 1 request per 30 SECONDS, far stricter than
 *     the usual 1-per-2s. This script makes exactly ONE parse request per run
 *     and caches the result, so a re-run costs zero requests.
 *   - Custom User-Agent identifying the project. From lib/http.ts.
 *   - Cache results, do not re-request. fetchJsonCached writes to data/raw/.
 *   - Content is CC-BY-SA 3.0 and MUST be attributed wherever displayed.
 *     The attribution string travels in the output JSON so it reaches the UI.
 *
 * Liquipedia is blocked from this project's cloud dev sandbox, so — like
 * research-wayback.ts and research-gosugamers.ts — this has to run on a real
 * machine. The row parsing below is a first pass written without ever having
 * seen this page's rendered markup; if it returns 0 rows, the cached HTML it
 * names has the real structure to correct it against.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { fetchJsonCached } from './lib/http.ts';

const API = 'https://liquipedia.net/dota2/api.php';
const PAGE = 'Tier_1_Tournaments';
/** Their documented cap for action=parse specifically. Not the 2s general limit. */
const PARSE_INTERVAL_MS = 30_000;

export const ATTRIBUTION =
  'Tournament, prize pool and tier data from Liquipedia, licensed CC-BY-SA 3.0.';

interface ParseResponse {
  parse?: { text?: { '*': string } };
  error?: { info: string };
}

async function fetchRenderedHtml(page: string, cacheDir: string): Promise<string> {
  const url = `${API}?action=parse&page=${encodeURIComponent(page)}&prop=text&format=json`;
  const { data, cached } = await fetchJsonCached<ParseResponse>(url, {
    cachePath: `${cacheDir}/liquipedia/${page.replace(/[^A-Za-z0-9]/g, '_')}.parse.json`,
    minIntervalMs: PARSE_INTERVAL_MS,
  });
  if (data.error) throw new Error(`${page} -> API error: ${data.error.info}`);
  const html = data.parse?.text?.['*'];
  if (!html) throw new Error(`${page} -> no HTML in API response`);
  console.log(cached ? '  (served from local cache — no request made)' : '  (fetched from Liquipedia)');
  return html;
}

/** Isolates one year's section: from its heading to the next heading of any level. */
function extractYearSection(html: string, year: string): string | null {
  const headingRe = new RegExp(`<h[1-6][^>]*id="${year}"[^>]*>[\\s\\S]*?</h[1-6]>`, 'i');
  const spanRe = new RegExp(
    `<h[1-6][^>]*>[\\s\\S]{0,200}?id="${year}"[\\s\\S]*?</h[1-6]>`,
    'i',
  );
  const start = headingRe.exec(html) ?? spanRe.exec(html);
  if (!start) return null;
  const from = start.index + start[0].length;
  const next = /<h[1-6][^>]*>/i.exec(html.slice(from));
  return html.slice(from, next ? from + next.index : html.length);
}

const stripTags = (html: string): string =>
  html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&ndash;/g, '–')
    .replace(/\s+/g, ' ')
    .trim();

const absoluteUrl = (src: string): string =>
  src.startsWith('//') ? `https:${src}` : src.startsWith('/') ? `https://liquipedia.net${src}` : src;

interface TeamRef {
  name: string | null;
  logo_url: string | null;
}

/** A winner/runner-up cell: a team-icon image plus a linked team name. */
function extractTeamCell(cellHtml: string): TeamRef {
  const img = /<img[^>]+src="([^"]+)"/i.exec(cellHtml);
  const links = [...cellHtml.matchAll(/<a[^>]*title="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)];
  // Skip the image's own File: link; the team name is the one with real text.
  const nameLink = links.find((m) => !/^File:/i.test(m[1] ?? '') && stripTags(m[2] ?? ''));
  const name = nameLink ? stripTags(nameLink[2] ?? '') : stripTags(cellHtml);
  // "TBD" is Liquipedia's placeholder for an unfinished event, not a team.
  const real = name && name.toUpperCase() !== 'TBD' ? name : null;
  return { name: real, logo_url: img ? absoluteUrl(img[1]!) : null };
}

interface TierOneRow {
  tournament: string | null;
  tournament_url: string | null;
  date: string | null;
  prizepool: string | null;
  location: string | null;
  /** Team count, Liquipedia's "P#" column. */
  participants: string | null;
  /**
   * Liquipedia highlights Valve-sponsored events (Majors and The
   * International) with a row class. Kept raw rather than reduced to a
   * boolean: the exact marker is the evidence, and what counts as "special"
   * changed across eras — which is the thing the season chart is meant to show.
   */
  row_classes: string | null;
  winner: TeamRef;
  runner_up: TeamRef;
}

function parseRows(sectionHtml: string): TierOneRow[] {
  const rows: TierOneRow[] = [];

  for (const rowMatch of sectionHtml.matchAll(/<tr([^>]*)>([\s\S]*?)<\/tr>/gi)) {
    const rowAttrs = rowMatch[1] ?? '';
    const rowHtml = rowMatch[2]!;
    const cells = [...rowHtml.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map((m) => m[1]!);
    // Header and spacer rows don't carry a full complement of columns.
    if (cells.length < 7) continue;
    if (/<th[^>]*>/i.test(rowHtml) && !/<td[^>]*>/i.test(rowHtml)) continue;

    // Column order, confirmed against real output:
    //   0 icon | 1 tournament | 2 date | 3 prize pool | 4 location | 5 P# |
    //   6 winner | 7 runner-up
    // The icon cell links to the tournament too, so fall back to it for the
    // name if the name cell somehow parses empty.
    const nameCell = cells[1] ?? '';
    const link =
      /<a[^>]+href="([^"]+)"[^>]*title="([^"]+)"/i.exec(nameCell) ??
      /<a[^>]+href="([^"]+)"[^>]*title="([^"]+)"/i.exec(cells[0] ?? '');
    const tournament = stripTags(nameCell) || (link ? link[2]! : null);
    if (!tournament) continue;

    rows.push({
      tournament,
      tournament_url: link ? absoluteUrl(link[1]!) : null,
      date: stripTags(cells[2] ?? '') || null,
      prizepool: stripTags(cells[3] ?? '') || null,
      location: stripTags(cells[4] ?? '') || null,
      participants: stripTags(cells[5] ?? '') || null,
      row_classes: /class="([^"]*)"/i.exec(rowAttrs)?.[1] ?? null,
      winner: extractTeamCell(cells[6] ?? ''),
      runner_up: extractTeamCell(cells[7] ?? ''),
    });
  }
  return rows;
}

async function main(): Promise<void> {
  const key = process.argv[2];
  const year = process.argv[3];
  if (!key || !year) {
    console.error('usage: npm run research:liquipedia -- <event-key> <year>   (e.g. ti08 2018)');
    process.exit(1);
  }

  const cacheDir = fileURLToPath(new URL(`../data/raw/${key}`, import.meta.url));

  console.log(`Liquipedia: ${PAGE}, year ${year}`);
  console.log('note: action=parse is capped at 1 request / 30s — this makes exactly one.\n');
  const html = await fetchRenderedHtml(PAGE, cacheDir);

  const debugPath = fileURLToPath(new URL(`../data/raw/${key}/liquipedia/${PAGE}.html`, import.meta.url));
  await mkdir(fileURLToPath(new URL(`../data/raw/${key}/liquipedia/`, import.meta.url)), { recursive: true });
  await writeFile(debugPath, html, 'utf8');
  console.log(`  rendered HTML saved for inspection (gitignored) -> ${debugPath}`);

  const section = extractYearSection(html, year);
  if (!section) {
    console.log(`\nNo "${year}" heading found. Check ${debugPath} for the real heading markup.`);
    process.exit(1);
  }

  const rows = parseRows(section);
  console.log(`\nparsed ${rows.length} row(s) for ${year}:\n`);
  for (const row of rows) {
    const marker = row.row_classes ? ` [${row.row_classes}]` : '';
    console.log(
      `  ${(row.date ?? '?').padEnd(24)} ${(row.tournament ?? '?').padEnd(34)} ` +
        `${(row.prizepool ?? '?').padEnd(12)} ${row.participants ?? '?'} teams${marker}`,
    );
    console.log(
      `      winner: ${(row.winner.name ?? '(not parsed)').padEnd(22)} ${row.winner.logo_url ?? '(no logo)'}`,
    );
  }

  if (rows.length === 0) {
    console.log(
      `\n0 rows parsed despite finding the ${year} section — the table markup differs from what this ` +
        `script guessed. Send me a chunk of ${debugPath} around the ${year} heading and I'll fix the parser.`,
    );
  }
  const missingLogo = rows.filter((r) => r.winner.name && !r.winner.logo_url);
  if (missingLogo.length) {
    console.log(`\n${missingLogo.length} row(s) have a winner but no logo URL — worth a look before charting.`);
  }

  const outDir = fileURLToPath(new URL('../data/research/', import.meta.url));
  await mkdir(outDir, { recursive: true });
  const outPath = `${outDir}${key}.liquipedia-tier1.json`;
  await writeFile(
    outPath,
    `${JSON.stringify(
      {
        _note:
          "Tier-1 tournaments for one year, from Liquipedia's own Tier_1_Tournaments page. Tier " +
          'classification, prize pool and winner are Liquipedia\'s, not inferred by this project. ' +
          'Prize pool is the TOTAL pool as listed, NOT the first-place share.',
        _generated_by: 'scripts/research-liquipedia-tier1.ts',
        _generated_at: new Date().toISOString(),
        _attribution: ATTRIBUTION,
        _source: {
          type: 'url',
          url: `https://liquipedia.net/dota2/${PAGE}`,
          retrieved_at: new Date().toISOString(),
        },
        event: key,
        year,
        row_count: rows.length,
        rows,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
  console.log(`\nwrote ${rows.length} row(s) -> ${outPath}`);
  console.log(`\n${ATTRIBUTION}`);
}

main().catch((error: unknown) => {
  console.error(`\nFAILED: ${(error as Error).message}`);
  process.exit(1);
});
